image: golang:1.11-stretch

before_script:

tests:
  script:
    - go get && go build
    - go test -v -coverprofile .coverage.txt
    - go tool cover -html=.coverage.txt
  artifacts:
    paths:
    - coverage.html
    expire_in: 1 week
